/*
 * adc_type.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */


#include "project.h"
#include "global.h"

#include "adc_type.h"
#include "joystick.h"
#include "logging.h"

/*****************************************************************************************
 *************** Port Wrapper Implementation for ADC signal                     **************************
 *****************************************************************************************/


/**
 * Default IN driver API - may be deleted if not required
 */
inline RC_t ADC_driverIn(ADC_data_t *const data)
{
    RC_t result=RC_SUCCESS;
    sint8_t x=0;
    sint8_t y=0;
	//Read data from the MCAL driver
    result = JOYSTICK_ReadPosition(&x, &y);
	//Scale it to the application type
    if(result == RC_SUCCESS)
    {
        data->m_x = (100 * x)/128;
        data->m_y = (100 * y)/128;
    }
	return result;
}

/**
 * Default IN driver API - may be deleted if not required
 */
inline RC_t ADC_driverOut(const ADC_data_t  *const data)
{
//#error "Add your code here"

	//Scale application data to drive format

	//Write scaled data to driver

	return RC_SUCCESS;
}
