/*
 * gpio_type.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */


#include "project.h"
#include "global.h"
#include "led.h"

#include "gpio_type.h"

/*****************************************************************************************
 *************** Port Wrapper Implementation for GPIO signal                     **************************
 *****************************************************************************************/


/**
 * Default IN driver API - may be deleted if not required
 */
inline RC_t GPIO_driverIn(GPIO_data_t *const data)
{
//#error "Add your code here"

	//Read data from the MCAL driver

	//Scale it to the application type

	return RC_SUCCESS;
}

/**
 * Default IN driver API - may be deleted if not required
 */
inline RC_t GPIO_driverOut(const GPIO_data_t  *const data)
{
	//Write scaled data to driver
    LED_Set(data->LED_Type, data->LED_State);
	return RC_SUCCESS;
}
