/*
 * lcd_type.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */



#ifndef LCD_TYPE_H_
#define LCD_TYPE_H_

#include "global.h"
#include "ugui.h"
/*****************************************************************************************
 *************** Type Definition for LCD signal                     **************************
 *****************************************************************************************/


typedef struct
{
    uint8 str;

} LCD_data_t;

#define LCD_INIT_DATA ((LCD_data_t){100})


/**
 * Default IN driver API - may be deleted if not required
 * \param LCD_data_t *const data : [OUT] scaled data read from the driver
 * \return RC_SUCCESS is all was ok, error code otherwise
 */
RC_t LCD_driverIn(LCD_data_t *const data);


/**
 * Default IN driver API - may be deleted if not required
 * \param const LCD_data_t  *const data : [IN] signal data for the driver, will be scaled in this function
 * \return RC_SUCCESS is all was ok, error code otherwise
 */
RC_t LCD_driverOut(const LCD_data_t  *const data);



#endif /* LCD_TYPE_H_ */

