/*
 * lcd_type.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */


#include "project.h"
#include "global.h"

#include "lcd_type.h"
#include "ugui.h"
#include "ugui_st7735.h"
#include "led.h"
#include "logging.h"

/*****************************************************************************************
 *************** Port Wrapper Implementation for LCD signal                     **************************
 *****************************************************************************************/


/**
 * Default IN driver API - may be deleted if not required
 */
inline RC_t LCD_driverIn(LCD_data_t *const data)
{
    

	//Read data from the MCAL driver

	//Scale it to the application type

	return RC_SUCCESS;
}

/**
 * Default IN driver API - may be deleted if not required
 */
inline RC_t LCD_driverOut(const LCD_data_t  *const data)
{
    char value[100];
    char str[20];
    uint8_t y;
    //GetResource(mutex);
    itoa(data->str , value, 10);
    y=data->str;
    //sprintf(str, "y: %d", y);
    //LOG_I(str,"");
    //UG_FillScreen(C_KHAKI);
    UG_FillFrame(12,38,100,60,C_KHAKI);
    UG_FontSelect(&FONT_10X16);
    UG_SetBackcolor(C_KHAKI);
    UG_SetForecolor(C_RED);
    
    UG_PutString(1, 5 , "Recvd Data: ");
    
    UG_PutString(15, 40,value);
    //ReleaseResource(mutex);
    //LED_Set(LED_YELLOW,LED_ON);
	return RC_SUCCESS;
}
