/*
 * pwm_type.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */


#include "project.h"
#include "global.h"

#include "pwm_type.h"

/*****************************************************************************************
 *************** Port Wrapper Implementation for PWM signal                     **************************
 *****************************************************************************************/


/**
 * Default IN driver API - may be deleted if not required
 */
inline RC_t PWM_driverIn(PWM_data_t *const data)
{
//#error "Add your code here"

	//Read data from the MCAL driver

	//Scale it to the application type

	return RC_SUCCESS;
}

/**
 * Default IN driver API - may be deleted if not required
 */
inline RC_t PWM_driverOut(const PWM_data_t  *const data)
{
    PWM_Clock_Start();
    RGB_PWM_green_Start();

	//Scale application data to drive format

    //RGB_PWM_green_WriteCompare(data->m_pwm);

	//Write scaled data to driver
    RGB_PWM_green_WriteCompare(data->m_pwm);
    
	return RC_SUCCESS;
}
