/**************************************************
 ** Software Component SWC_Remote
 ** autogenerated by H-DA RTE Generator
 **************************************************/

#include "rte.h"
#include "rte_signalpool.h"

#include "logging.h"
#include "swc_lcd.h"
#include "led.h"
#include "watchdog.h"

/* Runnables */
void run_setLcd()
{
    //LOG_I("run_setLcd","");
    //SetRelAlarm(alrm_error,100,1);
    RTE_LCD_pushPort(&LCD_signal);
    runnables.bit_field.run_setLcd=0;
    //CancelAlarm(alrm_error);
}
