/**************************************************
 ** Software Component SWC_Remote
 ** autogenerated by H-DA RTE Generator
 **************************************************/

#include "rte.h"
#include "rte_signalpool.h"

#include "logging.h"
#include "swc_joystick.h"
#include "led.h"
#include "watchdog.h"

/* Runnables */
void run_readJoystick()
{
   //LOG_I("run_readJoystick","");
    RC_t result = RC_ERROR;
    //SetRelAlarm(alrm_error,1,1);
    result = RTE_ADC_pullPort( &JOYSTICK_signal ); 
    runnables.bit_field.run_readJoystick=1;
    //CancelAlarm(alrm_error);
}
