/**************************************************
 ** Software Component SWC_Remote
 ** autogenerated by H-DA RTE Generator
 **************************************************/

#ifndef SWC_LCD_H
#define SWC_LCD_H


/* Runnables */
void run_setLcd();

#endif /* include guard */

