/**************************************************
 ** Software Component SWC_Remote
 ** autogenerated by H-DA RTE Generator
 **************************************************/

#ifndef SWC_BRAJELIGHT_H
#define SWC_BRAKELIGHT_H


/* Runnables */
void run_setBrakeLight();

#endif /* include guard */

