/**************************************************
 ** Software Component SWC_Control
 ** autogenerated by H-DA RTE Generator
 **************************************************/

#include "rte.h"
#include "rte_signalpool.h"

#include "logging.h"

#include "swc_control.h"
#include "led.h"
#include "ugui.h"
#include "watchdog.h"




/* Runnables */

void run_calculateControl()
{
    //LOG_I("run_calculateControl","");
    PWM_data_t enginvalue;
    GPIO_data_t brakevalue;
    LCD_data_t lcdvalue;
    char str[100];
    sint8_t x=0;
    uint8_t xx=0;
    ADC_data_t joystickvalue = RTE_ADC_get(&JOYSTICK_signal);
    //SetRelAlarm(alrm_error,1,1);
    if ( joystickvalue.m_x > 0)
    {
        enginvalue.m_pwm = (uint8_t) (2 * joystickvalue.m_x);
        RTE_PWM_set(&ENGINE_signal, enginvalue);
        brakevalue.LED_Type=LED_GREEN;
        brakevalue.LED_State=LED_OFF;
        RTE_GPIO_set(&BRAKELIGHT_signal,brakevalue);
        lcdvalue.str=enginvalue.m_pwm;
        x=joystickvalue.m_x;
        //sprintf(str, "x: %d", x);
        //LOG_I(str,"");
        //xx=enginvalue.m_pwm;
        //sprintf(str, "xx: %d", xx);
        //LOG_I(str,"");
        //lcdvalue.str=(uint8_t) (joystickvalue.m_x);
        RTE_LCD_set(&LCD_signal,lcdvalue);
        runnables.bit_field.run_calculateControl=1;
        //CancelAlarm(alrm_error);
    }
    else
    {
        enginvalue.m_pwm = 0;
        RTE_PWM_set(&ENGINE_signal, enginvalue);
        brakevalue.LED_Type=LED_GREEN;
        brakevalue.LED_State=LED_ON;
        RTE_GPIO_set(&BRAKELIGHT_signal,brakevalue);
        lcdvalue.str=enginvalue.m_pwm;
        //lcdvalue.str=(uint8_t) (joystickvalue.m_x);
        RTE_LCD_set(&LCD_signal,lcdvalue);
        runnables.bit_field.run_calculateControl=1;
        //CancelAlarm(alrm_error);
    }
}