/**************************************************
 ** Software Component SWC_Remote
 ** autogenerated by H-DA RTE Generator
 **************************************************/

#ifndef SWC_JOYSTICK_H
#define SWC_JOYSTICK_H


/* Runnables */
void run_readJoystick();

#endif /* include guard */

