/**************************************************
 ** Software Component SWC_Engine
 ** autogenerated by H-DA RTE Generator
 **************************************************/

#include "rte.h"
#include "rte_signalpool.h"

#include "logging.h"
#include "swc_engine.h"
#include "led.h"
#include "watchdog.h"

/* Runnables */
void run_setEngine()
{
    //LOG_I("run_setEngine","");
    //SetRelAlarm(alrm_error,1,1);
    RTE_PWM_pushPort(&ENGINE_signal);
    runnables.bit_field.run_setEngine=1;
    //CancelAlarm(alrm_error);
}
