/**************************************************
 ** Software Component SWC_Remote
 ** autogenerated by H-DA RTE Generator
 **************************************************/

#include "rte.h"
#include "rte_signalpool.h"

#include "logging.h"
#include "swc_brakelight.h"
#include "led.h"
#include "watchdog.h"

/* Runnables */
void run_setBrakeLight()
{
   //LOG_I("run_setBrakeLight","");
    //SetRelAlarm(alrm_error,1,1);
    RTE_GPIO_pushPort(&BRAKELIGHT_signal);
    runnables.bit_field.run_setBrakeLight=1;
    //CancelAlarm(alrm_error);
}
