/**************************************************
 ** Software Component SWC_Engine
 ** autogenerated by H-DA RTE Generator
 **************************************************/

#ifndef SWC_ENGINE_H
#define SWC_ENGINE_H


/* Runnables */
void ENGINE_getDecoder_run();

void ENGINE_setSpeed_run();

void run_setEngine();

#endif /* include guard */

